Realty/Realty/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('realtyapp.urls', namespace='realtyapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Realty/realtyapp/urls.py
from realtyapp import views
from django.urls import path

app_name = 'realtyapp'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('sale/', views.sale, name='sale'),
    path('rent/', views.rent, name='rent'),
    path('new_buildings/', views.new_buildings, name='new_buildings'),
    path('message/', views.message, name='message'),
    path('apartment/<int:id>/', views.apartment, name='apartment')
]

Realty/realtyapp/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=16, unique=True)

    def __str__(self):
        return self.name

class Metro(models.Model):
    name = models.CharField(max_length=32, blank=True)

class Room_count(models.Model):
    name = models.CharField(max_length=32, blank=True)

class Material(models.Model):
    name = models.CharField(max_length=32, blank=True)

class Balcony(models.Model):
    name = models.CharField(max_length=32, blank=True, null=True)

class Currency(models.Model):
    name = models.CharField(max_length=32, blank=True)

class Street(models.Model):
    name = models.CharField(max_length=32)

class Sity(models.Model):
    name = models.CharField(max_length=32, blank=True)

class Area_city(models.Model):
    name = models.CharField(max_length=32, blank=True)



class Apartment(models.Model):

    url_object = models.URLField()
    metro_name = models.ForeignKey(Metro, blank=True, null=True, on_delete=models.CASCADE)
    metro_distance = models.CharField(max_length=50, blank=True)
    metro_distance_number = models.CharField(max_length=32, blank=True)
    total_square = models.CharField(max_length=32, blank=True)
    living_square = models.CharField(max_length=32, blank=True)
    floor_number = models.CharField(max_length=32, blank=True)
    floor_total = models.CharField(max_length=32, blank=True)
    count_room = models.ForeignKey(Room_count, blank=True, null=True, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, blank=True, null=True, on_delete=models.CASCADE)
    balcony_type = models.ForeignKey(Balcony, blank=True, null=True, on_delete=models.CASCADE)
    is_home_appliances = models.CharField(max_length=32, blank=True)
    is_furniture = models.CharField(max_length=32, blank=True)
    year_public = models.CharField(max_length=32, blank=True)
    month_public = models.CharField(max_length=32, blank=True)
    day_public = models.CharField(max_length=32, blank=True)
    time_public = models.CharField(max_length=16, blank=True)
    cost = models.CharField(max_length=32, blank=True)
    currency = models.ForeignKey(Currency, blank=True, null=True, on_delete=models.CASCADE)
    house_number = models.CharField(max_length=32, blank=True)
    street = models.ForeignKey(Street, blank=True, null=True, on_delete=models.CASCADE)
    city = models.ForeignKey(Sity, blank=True, null=True, on_delete=models.CASCADE)
    area_city = models.ForeignKey(Area_city, blank=True, null=True, on_delete=models.CASCADE)
    advertising_object = models.CharField(max_length=70, blank=True)
    description = models.CharField(max_length=150, blank=True)
    category = models.ManyToManyField(Category)
    # image = models.ForeignKey(Images, blank=True, null=True, on_delete=models.CASCADE)

class Images(models.Model):
    # image = models.ImageField(upload_to='apartaments', blank=True, null=True)
    apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE)
    url_image = models.URLField()




class Message_user(models.Model):
    name = models.CharField(max_length=32)
    message = models.TextField()
    email = models.EmailField()
    create = models.DateTimeField(auto_now_add=True)
    telefone = models.CharField(max_length=16, blank=True)

Realty/realtyapp/forms.py
from django import forms
from .models import Message_user

class MessageForm(forms.ModelForm):
    name = forms.CharField(label='Имя',
                           widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))
    message = forms.CharField(label='Сообщение',
                              widget=forms.TextInput(attrs={'placeholder': 'Message', 'class': 'form-control'}))
    telefone = forms.CharField(label='Телефон',
                               widget=forms.TextInput(attrs={'placeholder': 'Telefone', 'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Message_user
        fields = '__all__'

Realty/realtyapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from realtyapp.models import Apartment, Category, Images
from .forms import MessageForm
from django.urls import reverse
from django.core.mail import send_mail

# Create your views here.
def main_view(request):
    return render(request, 'realtyapp/index.html', context={})

def sale(request):
    id_category = Category.objects.get(name='sale')
    sales = Apartment.objects.filter(category=id_category)
    return render(request, 'realtyapp/sale.html', context={'sales': sales})

def rent(request):
    id_category = Category.objects.get(name='rent')
    rents = Apartment.objects.filter(category=id_category)
    return render(request, 'realtyapp/rent.html', context={'rents': rents})

def new_buildings(request):

    return render(request, 'realtyapp/new_buildings.html', context={})

def message(request):
    if request.method == 'GET':
        message = MessageForm()
        return render(request, 'realtyapp/message.html', context={'message': message})
    else:
        message = MessageForm(request.POST)
        if message.is_valid():
            name = message['name'].value()
            email = message['email'].value()
            text_message = message['message'].value()
            # print(f'name  {name}')
            # print(f'email  {email}')
            # print(f'text_message  {text_message}')
            message.save()

            send_mail(
                'Response letter',
                f'{name} Ваше письмо получено {text_message}',
                '',
                [email],
                fail_silently=True,
            )
            return HttpResponseRedirect(reverse('realtyapp:index'))
        else:
            return render(request, 'realtyapp/message.html', context={'message': message})


def apartment(request, id):
    apartment = get_object_or_404(Apartment, id=id)
    categorys = apartment.category.all()
    for category in categorys:
        name_category = category.name
    images = Images.objects.filter(apartment=apartment)
    return render(request, 'realtyapp/apartment.html', context={'apartment': apartment, 'images': images,
                                                                'name_category': name_category})

Realty/realtyapp/templates/realtyapp/apartment.html
{% extends "base.html" %}

{% block title %}
  Квартира
{% endblock %}

{% block topic %}
    {% if name_category == "rent" %}
          <h1>Сдается</h1>
    {% endif %}
    {% if name_category == "sale" %}
        <h1>Продается</h1>
    {% endif %}
  <br>
  <h3>{{ apartment.count_room.name }}-комн. квартира, {{ apartment.total_square }} м.кв.,</h3>
              <h3>{{ apartment.floor_number }}/{{ apartment.floor_total }} этаж</h3>
              <h3>{{ apartment.street.name }}, {{ apartment.house_number }}, {{ apartment.city.name }}</h3>
              <br>
              <h2>{{ apartment.cost }} {{ apartment.currency.name }}</h2>
{% endblock %}

{% block whattopic %}

{% endblock %}

{% block content %}
    <h5>{{ apartment.description }}</h5>
    <br>
    <h5>Метро  ---  {{ apartment.metro_name.name }}  {{ apartment.metro_distance }}</h5>
    <br>
    <br>
    <h3>Информация об объекте</h3>
    <br>
    <h5>Комнат  {{ apartment.count_room.name }}</h5>
    <h5>Площадь  {{ apartment.total_square }}  кв.м</h5>
    <h5>Этаж  {{ apartment.floor_number }}/{{ apartment.floor_total }}</h5>
    <h5>Материал  {{ apartment.material.name }}</h5>
    <h5>{{ apartment.balcony_type.name }}</h5>
    <h5>{{ apartment.is_home_appliances }}</h5>
    <h5>{{ apartment.is_furniture }}</h5>
    <h5>Дата публикации  {{ apartment.year_public }} {{ apartment.month_public }} {{ apartment.day_public }}
      {{ apartment.time_public }}</h5>
    {% for image in images %}

        <img src="{{image.url_image}}">
        <br>
        <br>
    {% endfor %}

{% endblock %}

Realty/realtyapp/templates/realtyapp/index.html
{% extends "base.html" %}

{% block title %}
  Главная
{% endblock %}

{% block topic %}
  Сайт
{% endblock %}

{% block whattopic %}
  Недвижимости
{% endblock %}

{% block content %}

<div class="lg-img-wrap"><img class="lg-object lg-image" src="/api/catalog/sale/apartments/55228/image/2360916/"></div>

      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">



                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
{% endblock %}

Realty/realtyapp/templates/realtyapp/message.html
{% extends "base.html" %}

{% block title %}
  Сообщение
{% endblock %}

{% block topic %}
  Свяжитесь
  с нами
{% endblock %}

{% block whattopic %}
  Есть вопросы? У нас есть ответы.
{% endblock %}

{% block content %}
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

        <form method="post">
          {% csrf_token %}
          {{ message.as_p }}
          <br>
          <br>
          <div class="form-group">
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Отправить</button>
          </div>
        </form>
      </div>
    </div>
{% endblock %}

Realty/realtyapp/templates/realtyapp/new_buildings.html
{% extends "base.html" %}

{% block title %}
  Новостройки
{% endblock %}

{% block topic %}
  Новостройки
{% endblock %}

{% block content %}
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              Man must explore, and this is exploration at its greatest
            </h2>
            <h3 class="post-subtitle">
              Problems look mighty small from 150 miles up
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on September 24, 2019</p>
        </div>
        <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
            </h2>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on September 18, 2019</p>
        </div>
        <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              Science has not yet mastered prophecy
            </h2>
            <h3 class="post-subtitle">
              We predict too much for the next year and yet far too little for the next ten.
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on August 24, 2019</p>
        </div>
        <hr>
        <div class="post-preview">
          <a href="post.html">
            <h2 class="post-title">
              Failure is not an option
            </h2>
            <h3 class="post-subtitle">
              Many say exploration is part of our destiny, but it’s actually our duty to future generations.
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">Start Bootstrap</a>
            on July 8, 2019</p>
        </div>
        <hr>
        <!-- Pager -->
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
        </div>
      </div>
    </div>
{% endblock %}

Realty/realtyapp/templates/realtyapp/rent.html
{% extends "base.html" %}

{% block title %}
  Аренда
{% endblock %}

{% block topic %}
  Аренда
{% endblock %}

{% block whattopic %}
  Квартир
{% endblock %}

{% block content %}
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for item in rents %}
        <div class="post-preview">
          <a href="{% url 'realtyapp:apartment' id=item.id %}">
            <h2 class="post-title">
             <h3>{{ item.count_room.name }}-комн. квартира, {{ item.total_square }} м.кв.,</h3>
              <h3>{{ item.floor_number }}/{{ item.floor_total }} этаж</h3>
              <h3>{{ item.street.name }}, {{ item.house_number }}, {{ item.city.name }}</h3>
              <br>
              <h2>{{ item.cost }} {{ item.currency.name }}</h2>
            </h2>
            <h3 class="post-subtitle">
<!--              Problems look mighty small from 150 miles up-->
            </h3>
          </a>
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on September 24, 2019</p>-->
        </div>
        <br>
        <hr>
        <br>
        {% endfor %}
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.-->
<!--            </h2>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on September 18, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              Science has not yet mastered prophecy-->
<!--            </h2>-->
<!--            <h3 class="post-subtitle">-->
<!--              We predict too much for the next year and yet far too little for the next ten.-->
<!--            </h3>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on August 24, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              Failure is not an option-->
<!--            </h2>-->
<!--            <h3 class="post-subtitle">-->
<!--              Many say exploration is part of our destiny, but it’s actually our duty to future generations.-->
<!--            </h3>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on July 8, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->
<!--         Pager-->
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
        </div>
      </div>
    </div>
{% endblock %}

Realty/realtyapp/templates/realtyapp/sale.html
{% extends "base.html" %}

{% block title %}
  Продажа
{% endblock %}

{% block topic %}
  Продажа
{% endblock %}

{% block whattopic %}
  Квартир
{% endblock %}



{% block content %}
        <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for item in sales %}
        <div class="post-preview">
          <a href="{% url 'realtyapp:apartment' id=item.id %}">
            <h2 class="post-title">
             <h3>{{ item.count_room.name }}-комн. квартира, {{ item.total_square }} м.кв.,</h3>
              <h3>{{ item.floor_number }}/{{ item.floor_total }} этаж</h3>
              <h3>{{ item.street.name }}, {{ item.house_number }}, {{ item.city.name }}</h3>
              <br>
              <h2>{{ item.cost }} {{ item.currency.name }}</h2>
            </h2>
            <h3 class="post-subtitle">
<!--              Problems look mighty small from 150 miles up-->
            </h3>
          </a>
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on September 24, 2019</p>-->
        </div>
        <br>
        <hr>
        <br>
        {% endfor %}
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.-->
<!--            </h2>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on September 18, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              Science has not yet mastered prophecy-->
<!--            </h2>-->
<!--            <h3 class="post-subtitle">-->
<!--              We predict too much for the next year and yet far too little for the next ten.-->
<!--            </h3>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on August 24, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              Failure is not an option-->
<!--            </h2>-->
<!--            <h3 class="post-subtitle">-->
<!--              Many say exploration is part of our destiny, but it’s actually our duty to future generations.-->
<!--            </h3>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on July 8, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->
        <!-- Pager -->
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
        </div>
      </div>
    </div>
{% endblock %}

Realty/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="/">карта сайта</a>

<!--      <a class="post-title" href="index.html">глааная</a>-->
<!--      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        Menu-->
<!--        <i class="fas fa-bars"></i>-->
<!--      </button>-->
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'realtyapp:index' %}">главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'realtyapp:sale' %}">продажа</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'realtyapp:rent' %}">аренда</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'realtyapp:new_buildings' %}">новостройки</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'realtyapp:message' %}">сообщение</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'realtyapp:message' %}">телефон</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{% block topic %}{% endblock %}</h1>
            <span class="subheading">{% block whattopic %}{% endblock %}</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

Realty/templates/startbootstrap-clean-blog-gh-pages/startbootstrap-clean-blog-gh-pages/about.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>